feat(minecraft): add celebi
PixelmonToGo/gitops-k8s pull request #727
Opened 2022-04-13 15:21 UTC by LooterToGo

Depends on #710 
Depends on #740

2022-04-14 00:25 UTC, ChipWolf requested changes

2022-04-14 00:25 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
Celebi in the development environment needs to be ready with the current stacked (base & includes) versions before this will be accepted.

2022-04-14 00:25 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +            type: LoadBalancer
I think we have an IP shortage, so an external service will likely need to be decommissioned prior to this going live.

2022-04-14 00:25 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
If the Tebex token will be different for Pikachu and Celebi, we'll likely need to supplement this with a different secret.

2022-04-14 00:25 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +                - germany
I presume this will live in the Canada region rather than any regions in EMEA?

2022-04-14 14:44 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
How do we proceed with this. @ChipWolf

2022-04-14 15:02 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +            type: LoadBalancer
https://github.com/PixelmonToGo/gitops-k8s/pull/710  Should be fine once we merge this, the world & plugins are in Gdrive saved @ChipWolf

2022-04-14 15:03 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
Yes it should be different, how do we proceed? @ChipWolf

2022-04-14 15:05 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +                - germany
I agree, I changed it.

2022-04-19 22:34 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
Please add another secret to override the Tebex key for this deployment

2022-04-19 22:35 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +            type: LoadBalancer
Screenshot confirmation and I'll resolve this conversation

2022-04-19 22:35 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
Change the generic packs and dd version lines with the latest ones from the Pikachu dev server in Celebi dev (in a new PR)

2022-04-19 22:40 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
I already did it in this pr @ChipWolf

2022-04-19 22:42 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +            type: LoadBalancer
> 

https://i.imgur.com/hUX4ON8.png

2022-04-19 22:42 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +            type: LoadBalancer
@ChipWolf

2022-04-19 22:43 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
> Please add another secret to override the Tebex key for this deployment
Got no idea how to do that @ChipWolf

2022-04-19 22:43 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
Need another PR to do the same in dev first

2022-04-19 22:44 UTC, ChipWolf commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
Copy the secret yaml, add a new one?

2022-04-19 23:09 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      GENERIC_PACKS: "forge-v10.2.0+es.zip"
@ChipWolf Made a commit to do the same in dev & prod in this pr.

2022-04-20 17:47 UTC, LooterToGo commented on minecraft/minecraft/minecraft-forge-celebi.yaml
> +      name: "minecraft-helm-values"
Done

2022-04-21 01:43 UTC, ChipWolf requested changes

2022-04-21 01:43 UTC, ChipWolf commented on minecraft/minecraft/minecraft-helm-values-celebi.yaml
> +  namespace: minecraft-dev
Wrong namespace

2022-04-21 01:43 UTC, ChipWolf commented on setup/bootstrap-vault.sh
> +  kvault "minecraft/minecraft/minecraft-helm-values-celebi.txt"
Alphebetise

2022-04-21 01:52 UTC, LooterToGo commented on setup/.env.sample
> +export MC_CELEBI_TEBEX_KEY=""
I don't think it was introduced in the another PR @ChipWolf

2022-04-21 01:59 UTC, LooterToGo commented on setup/bootstrap-vault.sh
> +  kvault "minecraft/minecraft/minecraft-helm-values-celebi.txt"
Review

2022-04-21 02:02 UTC, LooterToGo commented on minecraft/minecraft/minecraft-helm-values-celebi.yaml
> +  namespace: minecraft-dev
Resolved.

2022-04-21 02:33 UTC, merged