fix(minecraft-dev/celebi): add helm values
PixelmonToGo/gitops-k8s pull request #740
Opened 2022-04-19 23:28 UTC by LooterToGo

2022-04-19 23:32 UTC, ChipWolf requested changes
The new secret needs to be added at the bottom in valuesFrom and added to the bootstrap-vault script

2022-04-19 23:32 UTC, ChipWolf commented on minecraft-dev/minecraft/minecraft-helm-values-celebi.txt
> +  GENERIC_PACKS_PREFIX: "$MC_DEV_PACK_URL"
Only the Tebex env var should be in here

2022-04-20 00:53 UTC, ChipWolf requested changes

2022-04-20 00:53 UTC, ChipWolf commented on minecraft-dev/minecraft/minecraft-helm-values.txt
> +  CFG_TEBEX_KEY: "$MC_TEBEX_CELEBI_KEY"
This change is probably unintentional

2022-04-20 12:25 UTC, LooterToGo commented on minecraft-dev/minecraft/minecraft-helm-values.txt
> +  CFG_TEBEX_KEY: "$MC_TEBEX_CELEBI_KEY"
Ya it's unintentional. Blind eyes yesterday.

2022-04-20 12:29 UTC, LooterToGo commented on minecraft-dev/minecraft/minecraft-helm-values-celebi.txt
> +  GENERIC_PACKS_PREFIX: "$MC_DEV_PACK_URL"
Should be sorted out now. @ChipWolf

2022-04-20 12:29 UTC, LooterToGo commented on minecraft-dev/minecraft/minecraft-helm-values.txt
> +  CFG_TEBEX_KEY: "$MC_TEBEX_CELEBI_KEY"
Issue resolved.

2022-04-21 01:30 UTC, merged